title: SAP Stammtisch Overview
description: Infos and Dates of SAP Stammtisch events
show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day
url: "https://sapstammtisch.github.io/Overview-beta"
